# Generated by Django 3.1 on 2020-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
