# Generated by Django 3.1 on 2020-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
